server:
  port: 8080
spring:
  application:
    name: shortify
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  h2:
    console:
      enabled: true
  url:
    root: http://localhost:8080/